CREATE TABLE IF NOT EXISTS chat (
    id SERIAL,
    name VARCHAR(100) DEFAULT 'New Chat',
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS message (
    id SERIAL,
    chat_id INT NOT NULL,
    by VARCHAR(50) NOT NULL,
    data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (chat_id) REFERENCES chat (id) ON DELETE CASCADE
);